### ISSUE TITLE
🐞 - Unknown compiler option 'verbatimModuleSyntax'

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/linters#505]
### Playground Link

https://github.com/taiga-family/maskito/pull/1428

### Description

https://github.com/taiga-family/linters/blob/304ddc4f478ef91aaa0e54dba1d93e2f77d79a94/projects/tsconfig/tsconfig.json#L88

https://github.com/taiga-family/linters/commit/8b23332fab807731c4e575d3ef64dc27cd8f35ef

### Taiga UI version

@taiga-ui/tsconfig@0.129.0

**Comment by splincode** [comment]
@nsbarsukov which typescript version do you use?

https://github.com/quasarframework/quasar/issues/16826#issuecomment-1950250083

**Comment by nsbarsukov** [comment]
[`4.9.5`](https://github.com/taiga-family/maskito/blob/b19ae7383851e52c80a1802b73219ed4d878892d/package.json#L129)

Should I update it to `5.0.0` to fix issue ?

**Comment by splincode** [comment]
Yes, please update to 5.x
